name: Code formatting

on: [push]

jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm install .
            - run: npx prettier --check './**/*.{ts,js,json}'
